# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 21:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a01', '0002_auto_20170926_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='composer',
            field=models.CharField(default=21312, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='movie',
            name='screenplay',
            field=models.CharField(default=213, max_length=50),
            preserve_default=False,
        ),
    ]
